### PR TITLE
fix: Static assets fail to load

### LINKED ISSUE #38: Static assets fail to load
https://github.com/power-guard/pg_monitor_dashboard/blob/b64298264760097be4f6aa4aab659985638878d9/src/components/Head.tsx#L13

https://github.com/power-guard/pg_monitor_dashboard/blob/b64298264760097be4f6aa4aab659985638878d9/src/pages/index.tsx#L17

Links to these images are hardcoded and do not use the `basePath` attribute of `next.config.js`.
As a result, they are not loaded properly on the production environment (server returns 404).

Proposed solution:
Change paths to `/dashboard/favicon.ico`  `/dashboard/error.svg` respectively.

Not sure how this will impact the development environment. Some things might need to be reworked in order for everything to work out cleanly. For reference, this is the content of `next.config.js` in production:

```javascript
module.exports = {

  basePath: '/dashboard',

  async rewrites() {
    if (process.env.NODE_ENV === 'production') {
      return [];
    }

    return [
      {
        source: '/api/:path*',
        destination: 'http://localhost:23500/api/:path*',
      },
    ];
  },
};
```

Note:

I experimented with adding the following rewrites, but they failed. Let me know if I did something wrong here.

```javascript
module.exports = {

  basePath: '/dashboard',

  async rewrites() {
    if (process.env.NODE_ENV === 'production') {
      return [
        {
          source: '/favicon.ico',
          destination: '/dashboard/favicon.ico',
        },
        {
          source: '/error.svg',
          destination: '/dashboard/error.svg',
        },
      ];
    }

    return [
      {
        source: '/api/:path*',
        destination: 'http://localhost:23500/api/:path*',
      },
    ];
  },
};
```

### PR DESCRIPTION
**Pull request by jcmtallon**
## Related Issue
Resolves #38

### CODE REVIEW

File: src/utils/environmentUtils.ts [hunk 1]
```diff
@@ -0,0 +1,3 @@
+export const getStaticFilePath = (path: string): string => {
+  return process.env.NODE_ENV === 'production' ? `/dashboard${path}` : path;
+};
```
Comment (jcmtallon) [inline src/utils/environmentUtils.ts:3]: Not the smartest solution but could do the trick for now. You can give it a try if you want. 
I'm going to investigate about rewrite a little bit more any way. It is not ideal that we have to use this util for every single static file.

**Review by power-guard — APPROVED** [review]
Looks good for the time being. Can deal with the bigger implications if and when it's necessary.
